version: "3.3"
services:
  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  edge:
    image: edge:latest
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - redis
  worker:
    build: ./workers
    depends_on:
      - redis
